// ╔═══════════════════════════════════════╗
// ║  @Ultr                                ║
// ║  CrossOver Neon                       ║
// ╚═══════════════════════════════════════╝

//@version=5
indicator("CrossOver Neon (@Ultr)", shorttitle = "CrossOver(@Ultr.)", overlay = true)

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Colors  ═══ 

var grpColor = " ═══ Colores ═══ "
color colorZero = color.new(#e91e63, na)  // color Fucxia
color colorFirs = color.new(#33ffac, na)  // color Verde
color colorSeco = color.new(#eedd45, na)  // color Amariñllo
color colorThir = color.new(#e65100, na)  // color Naranja
color colorFour = color.new(#00ffd5, na)  // color Menta
color colorFift = color.new(#12cef8, na)  // color Celeste
color colorSixt = color.new(#0034c5, na)  // color Azul

var grpShadow = " ═══ Shadow ═══ "
color colorLong  = input.color(#12cef8, title = "Long", group = grpShadow, inline = "Shad")
color colorShort = input.color(#e91e63, title = "Short", group = grpShadow, inline = "Shad")

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Inputs  ═══

var grpLong  = " ═══ EMAS ═══ "
eMa8      = input.bool(defval = true, title = "", group = grpLong, inline = 'ema8')
eMa20     = input.bool(defval = true, title = "", group = grpLong, inline = 'ema20')
eMa55     = input.bool(defval = true, title = "", group = grpLong, inline = 'ema55')
eMa200    = input.bool(defval = true, title = "", group = grpLong, inline = 'ema200')

length8    = input(8,    title = "Extensión",  group = grpLong, inline = 'ema8')
length20   = input(20,   title = "Extensión",  group = grpLong, inline = 'ema20')
length55   = input(55,   title = "Extensión",  group = grpLong, inline = 'ema55')
length200  = input(200,  title = "Extensión",  group = grpLong, inline = 'ema200')

lengthFast = input(8,    title = "Min MA",      group = grpLong)
lengthMed  = input(20,   title = "Med MA",      group = grpLong)
lengthSlow = input(55,   title = "Max MA",      group = grpLong)

length          = input(12)
transparencia   = input(100)

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Options  ═══

string optionMa	= input.string("SMA", "Tipo de MM", options = ["EMA", "SMA", "RMA", "WMA", "VWMA"])

//  ══════════════
//  ═══  Neon  ═══
//  ═══  Types  ═══

type OHL
    float O = open
    float H = high
    float L = low
    float C = close
    float V = volume

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Functions  ═══

ma(source, length, type) =>
    type == "SMA" ? ta.sma(source, length) :    // Media Movil Simple
     type == "EMA" ? ta.ema(source, length) :   // Media Movil Exponencial
     type == "RMA" ? ta.rma(source, length) :   // Media Movil
     type == "WMA" ? ta.wma(source, length) :   // Media Movil Ponderada
     type == "VWMA" ? ta.vwma(source, length) : // Media Movil Ponderada por volumen
     na

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Instances  ═══
ohl = OHL.new()

ma8   = ma(ohl.C, length8,    optionMa)
ma12  = ma(ohl.C, length,     optionMa)
ma20  = ma(ohl.C, length20,   optionMa)
ma55  = ma(ohl.C, length55,   optionMa)
ma200 = ma(ohl.C, length200,  optionMa)

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Math  ═══

float maHeight = ta.percentrank(ma12, 100)
float transparency = math.min(80, 100 - maHeight)

float maFast       = ma(ohl.C, lengthFast, optionMa)
float maMed        = ma(ohl.C, lengthMed,  optionMa)
float maSlow       = ma(ohl.C, lengthSlow, optionMa)

bool signal         = maFast > maMed
color colorCrOver   = signal ? colorLong : colorShort

//  ═══  CrossOver  ═══
bool crossOver8     = ta.crossover(maFast, maSlow)
bool crossOver20    = ta.crossover(maFast, maSlow)
bool crossUnder     = ta.crossunder(maFast, maSlow)

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Display EMAS  ═══

//  ═══  Ma 8  ═══
plot(ma8, color = color.new(colorCrOver,80), linewidth = 8,  editable = false)
plot(ma8, color = color.new(colorCrOver,90), linewidth = 16, editable = false)
plot(ma8, color = color.new(colorCrOver,95), linewidth = 32, editable = false)
plot(ma8, color = color.new(colorCrOver,98), linewidth = 40, editable = false)

//  ═══  Ma 20  ═══
plot(ma55, color = color.new(colorCrOver,80), linewidth = 8,  editable = false)
plot(ma55, color = color.new(colorCrOver,90), linewidth = 16, editable = false)
plot(ma55, color = color.new(colorCrOver,95), linewidth = 32, editable = false)
plot(ma55, color = color.new(colorCrOver,98), linewidth = 40, editable = false)

plot(eMa8 ? ma8 : na,     color = color.new(colorCrOver,30), linewidth = 2, editable = false)
// plot(eMa20 ? ma20 : na,    color = color.new(colorCrOver,30), linewidth = 2, editable = false)
// plot(eMa55 ? ma55 : na,   color = color.new(colorCrOver,30), linewidth = 2, editable = false)
plot(eMa200 ? ma200 : na, color = color.new(colorSixt, 90),  linewidth = 2, editable = false, title = "Ma 200", style = plot.style_area)

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Shadow  ═══
maPlot8   = plot(ma8,  "MA 8", color = color.new(colorCrOver,30), editable=false)
maPlot20  = plot(ma20,  "MA 20", color = color.new(colorCrOver,30), editable=false)
maPlot55  = plot(ma55,  "MA 55", color = color.new(colorCrOver,30), editable=false)

//  20 MA
// color maCrossOver20 = ma8 > ma20 ? colorLong : colorShort
// fill(maPlot8, maPlot20, maCrossOver20, "CrossOver 20")

//  55 MA
fill(maPlot8, maPlot20, color = color.new(colorCrOver,80), title = "CrossOver")

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Line Cross  ═══

bool maRising  = ta.rising(ma12, 1)
color lineCross = maRising ? color.new(colorLong, transparencia-60) : color.new(colorShort, transparencia-60)
plot(ma20, title = "Operativa", color = lineCross, linewidth = 5, editable = false)

//  ═══════════════
//  ═══  Cross  ═══
//  ═══  Operativa  ═══
buyCross = ta.crossover(ma8, ma55)
sellCross = ta.crossunder(ma8, ma55)

plotshape(series = buyCross,  style = shape.triangleup, location = location.belowbar, color = color.new(colorLong,40), text = "Buy", size = size.tiny)
plotshape(series = sellCross, style = shape.triangledown, location = location.abovebar, color = color.new(colorShort,40), text = "Sell", size = size.tiny)
